mikegazdag/prodminder_web

lib/conditions_importer.rb, lib/screenings_importer.rb
CSV importers for google spreadsheet
=> Add csv importers

db/migrate/20150226120000_create_conditions.rb, db/migrate/20150226120000_create_config.rb, db/migrate/20150226120000_create_reminders.rb, db/migrate/20150226120000_create_screenings.rb, db/migrate/20150226120000_create_sessions.rb, db/migrate/20150226120000_create_users.rb
@mikegazdag @Slothra - Please take a look at these migrations. Thanks!
=> Add migrations to create tables

app/actions.rb
Added actions i think the URL's make sense but I would like feedback
=> Add actions

spec_helper.rb
Not yet done: models and database connector
=> Add spec_helper

Gemfile.lock, app/actions.rb
Action file was missing a `end` to a an `if`.
=> Fix action file

app/actions.rb, app/views/layout.slim, app/views/stylesheets/pages/dashboard.sass, app/views/stylesheets/pages/index.sass
Add the functionality to pass a class to the HTML body so can we write specific styles to for each layout. Super handy!
=> Add body classes to our templates

app/actions.rb, app/views/index.slim, app/views/login.slim, app/views/stylesheets/pages/index.sass, app/views/stylesheets/pages/login.sass, app/views/stylesheets/screen.sass
Add a mother friggen login page!
=> Add login page

app/spec/test_the_cards.rb
Not sure about the validity of these without having a complete Card model yet.
=> Add Rspec test for cards.

app/views/_app_footer.slim, app/views/_app_header.slim, app/views/dashboard.slim, app/views/stylesheets/pages/dashboard.sass
Make the header and footer into paritals
=> Add partials for the dashboard

Gemfile, config/environment.rb
Problems with getting correct ports to open out of Vagrant / Virtualbox and to the Mailgun API (port 587?)
=> Add Mailgun

app/views/layout.slim, app/views/stylesheets/pages/dashboard.sass, public/javascripts/site.js
Tweaks to make the dashboard a little more responsive
=> Add responsive for the dashboard

Gemfile.lock, app/actions.rb, app/views/dashboard_email_validate.slim, app/views/footer.slim, app/views/index.slim, app/views/layout.slim, app/views/stylesheets/components/buttons.sass, app/views/stylesheets/components/footer.sass, app/views/stylesheets/pages/404.sass, app/views/stylesheets/pages/dashboard.sass, app/views/stylesheets/pages/dashboard_email_validate.sass, app/views/stylesheets/pages/index.sass, app/views/stylesheets/screen.sass, app/views/stylesheets/setup/animations.sass, app/views/stylesheets/setup/variables.sass, app/views/x404.slim, config/compass.config
Did a bunch of shit in this pull request, some general house keeping as well as general tweaking. 
**Not ideal** but not really worth it going separate branches
* Add dashboard email validation page
* Update `actions.rb`fie and comment out unused routes. Turn on routes as we use t
* Add `buttons.sass` sheet to share button styles 
* Misc house keeping issues dealing with relative pathing and whitespace
=> Add email validated and bunch of house keeping

app/helper_methods.rb
Include name in 'from' address, switch to HTML and ERB friendly message body format. @mikegazdag @Slothra
=> Update Mailgun helper method 

app/views/dashboard.slim, app/views/stylesheets/components/radio-switch.sass, public/javascripts/site.js
Updated the radio buttons! I also put the jquery in the site.js file for how this works. 
Lastly, they work by appending the HTML attr `checked` on to the `select` element.
=> New radio buttons!

app/views/stylesheets/pages/index.sass
Damn it, fixed the file name in index.sass masthead
=> Opps forgot to update file name in styles

app/actions.rb, app/views/_app_condition_cards.slim, app/views/_app_dev_bashboard.slim, app/views/_app_new_user_welcome.slim, app/views/dashboard.slim, app/views/layout.slim, app/views/stylesheets/app/app-dashboard.sass, app/views/stylesheets/app/condition-cards.sass, app/views/stylesheets/app/dev-mode-bashboard.sass, app/views/stylesheets/screen.sass
Hey @beforeyouknowit and @Slothra ! 
I've added a bunch of stuff tonight! I started the new_user/current_user workflows here.
* Add `@current_user_logged_in` variable to `actions.rb`. It's "almost" done, I'm treating it like the our email login method is working and showing/hiding content based on the value of the variable. `@current_user_logged_in` still needs to get set from the `/dashboard/validate` page :) 
* I've added `# TODO` notes to the routes that'll need some logic to be added. Feel free to update! 
* Quick note: `/login` will set `@current_user_logged_in = true`, you won't see new-user onboarding workflow 
* Likewise: `/logout` will set `@current_user_logged_in = false`, and go back to `/dashboard` and you'll see our onboarding workflow.
* Secondary note, in the top of …
=> Add dev/admin console and add current_user_logged_in variable to app

app/views/footer.slim, app/views/index.slim, app/views/stylesheets/app/condition-cards.sass, app/views/stylesheets/components/site-footer.sass, app/views/stylesheets/pages/index.sass
* Support multi pages
* Homepage tweaks
=> Tweak the footer clean up the redundancy on home styles

app/actions.rb, app/helper_methods.rb
=> Add current_user_logged_in session variable

app/actions.rb, db/migrate/20150301152000_add_custom_id.rb, db/schema.rb
Migration for the user table (adds custom_id field)
=> Renames actived_on to activated_on adds custom_id to users

app/actions.rb
=> Adds pseudocode for validates

app/actions.rb, app/helper_methods.rb, app/models/user.rb, app/views/_app_condition_cards.slim
=> Add gender and age sorting

app/actions.rb, app/helper_methods.rb, app/views/_app_condition_cards.slim, app/views/_app_dev_bashboard.slim, app/views/_app_footer.slim, app/views/dashboard.slim
=> Large refactor of sessions management

db/migrate/20150302000500_change_reminders_column_type.rb
=> Migration for reminders to change user id type

app/views/_app_new_user_form.slim, app/views/stylesheets/app/card-new-user.sass, app/views/stylesheets/app/condition-cards.sass, app/views/stylesheets/app/user-email-validate.sass, app/views/stylesheets/components/forms.sass, public/javascripts/site.js
Checked the shit of this new feature and nothing is broken! 
I replaced the birthday form elements with two `select` lists!
=> Replace birthday form elements with select lists

app/views/_app_condition_cards.slim, app/views/stylesheets/app/app-header.sass, app/views/stylesheets/app/condition-cards.sass, app/views/stylesheets/components/radio-switch.sass
* Remove `My Account` from navbar
Supposed to look like:
=> Update condition card switch styles

app/actions.rb, app/views/_app_new_user_form.slim, app/views/stylesheets/app/card-new-user.sass, app/views/stylesheets/components/forms.sass, app/views/stylesheets/pages/404.sass, app/views/stylesheets/pages/index.sass, app/views/x404.slim
=> More tweaks

app/views/_app_new_user_welcome.slim, app/views/stylesheets/app/card-new-user.sass, app/views/stylesheets/app/condition-cards.sass
=> Style new user welcome message
